name: FRC Build & Test
on: [push, pull_request]

# not sure how many minutes we get so for niwnwe stop
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2-beta
    - name: FRC Build & Test
      uses: ewpratten/FRC-actions@v1
      with:
        build_mode: 'build'
